# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=50)),
                ('position', models.IntegerField()),
                ('yt_id', models.CharField(max_length=20)),
                ('spotify_id', models.CharField(max_length=20)),
            ],
        ),
    ]
