# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='spotify_id',
            field=models.CharField(max_length=40),
        ),
    ]
