# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_list', '0003_auto_20160211_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='artist',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='songs',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
