# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_list', '0004_auto_20160211_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Playlists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('spotify_id', models.CharField(max_length=40)),
                ('songs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify_list.Songs')),
            ],
        ),
        migrations.AddField(
            model_name='genres',
            name='playlists',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify_list.Playlists'),
        ),
    ]
