# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_list', '0005_auto_20160211_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlists',
            name='yt_id',
            field=models.CharField(default='NA', max_length=20),
        ),
    ]
