# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 22:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_list', '0006_playlists_yt_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('short_name', models.CharField(max_length=10)),
                ('playlist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='spotify_list.Playlists')),
            ],
        ),
    ]
