# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_list', '0007_countries'),
    ]

#     operations = [
#         migrations.RemoveField(
#             model_name='countries',
#             name='playlist',
#         ),
#         migrations.AddField(
#             model_name='countries',
#             name='id',
#             field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
#             preserve_default=False,
#         ),
#     ]
