# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 23:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_list', '0008_auto_20160211_2305'),
    ]

    # operations = [
    #     migrations.DeleteModel(
    #         name='Countries',
    #     ),
    # ]
