# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 23:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_list', '0009_delete_countries'),
    ]

    # operations = [
    #     migrations.RemoveField(
    #         model_name='countries',
    #         name='playlist',
    #     ),
    #     migrations.DeleteModel(
    #         name='Countries',
    #     ),
    # ]
