# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion    


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_list', '0010_auto_20160211_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('short_name', models.CharField(max_length=10)),
            ],
        )
    ]
