# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_list', '0011_auto_20160211_2344'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Countries',
        ),
        migrations.RemoveField(
            model_name='playlists',
            name='spotify_id',
        ),
        migrations.RemoveField(
            model_name='playlists',
            name='yt_id',
        ),
    ]
