# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_list', '0012_auto_20160214_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlists',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='songs',
            name='artist',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='songs',
            name='title',
            field=models.CharField(max_length=140),
        ),
    ]
